from __future__ import annotations

import json
from pathlib import Path

from idea2thesis.agents import build_agent_tasks, passing_reviewer_results
from idea2thesis.contracts import (
    AgentResult,
    AgentStatus,
    ArtifactRef,
    ExecutionReport,
    JobPlan,
    JobSnapshot,
    ParsedBrief,
)
from idea2thesis.execution_policy import CommandRequest
from idea2thesis.executor import LocalCommandExecutor
from idea2thesis.storage import JobPaths


class SupervisorOrchestrator:
    def build_plan(self, brief: ParsedBrief) -> JobPlan:
        category = (
            "data_analysis_project"
            if any("分析" in item for item in brief.requirements)
            or any("分析" in item for item in brief.tech_hints)
            else "full_stack_app"
        )
        stack_policy = "python-data" if category == "data_analysis_project" else "fastapi-react"
        return JobPlan(
            project_category=category,
            stack_policy=stack_policy,
            review_criteria=[
                "requirements_alignment",
                "engineering_quality",
                "delivery_readiness",
            ],
            retries={"code_eval": 1},
            tasks=build_agent_tasks("", brief.title),
        )

    def run_job(
        self,
        job_id: str,
        brief: ParsedBrief,
        paths: JobPaths,
        executor: LocalCommandExecutor,
    ) -> JobSnapshot:
        plan = self.build_plan(brief)
        plan.tasks = build_agent_tasks(str(paths.workspace_dir), brief.title)

        project_readme = paths.workspace_dir / "README.md"
        thesis_draft = paths.artifacts_dir / "thesis-draft.md"
        verification_report_path = paths.artifacts_dir / "verification-report.json"

        project_readme.write_text(
            f"# {brief.title}\n\nGenerated by idea2thesis.\n",
            encoding="utf-8",
        )
        thesis_draft.write_text(
            f"# {brief.title} Thesis Draft\n\n## 摘要\n\n自动生成初稿。\n",
            encoding="utf-8",
        )

        report = executor.run(
            CommandRequest(
                executable="python",
                arguments=["-c", "print('verification ok')"],
                working_directory=paths.workspace_dir,
                purpose="code_eval",
                requires_network=False,
            )
        )
        verification_report_path.write_text(
            json.dumps(report.model_dump(), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

        reviewer_results = passing_reviewer_results()
        agent_statuses = [
            AgentStatus(role=task.role, status="done", summary=task.objective)
            for task in plan.tasks
        ]
        agent_statuses.extend(
            AgentStatus(role=result.role, status="done", summary=result.summary)
            for result in reviewer_results
            if result.role not in {status.role for status in agent_statuses}
        )

        return JobSnapshot(
            job_id=job_id,
            stage="completed",
            status="completed",
            agents=agent_statuses,
            artifacts=[
                ArtifactRef(kind="project_readme", path=str(project_readme)),
                ArtifactRef(kind="thesis_draft", path=str(thesis_draft)),
                ArtifactRef(kind="verification_report", path=str(verification_report_path)),
            ],
            validation_state="completed",
            final_disposition="completed",
        )
